name: unit tests
on:
  push:
    branches-ignore:
      - documentation
jobs:
    standards:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: Set up Python 3.11
              uses: actions/setup-python@v4
              with:
                python-version: "3.11"
            - name: init
              run: make dev-init
            - name: run-checks
              run: make standards
    unit-tests:
        runs-on: ubuntu-latest
        needs: standards
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: Set up Python 3.11
              uses: actions/setup-python@v4
              with:
                python-version: "3.11"
            - name: init
              run: make dev-init
            - name: unit-tests
              run: make test